name: Static Analysis
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2']

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse
